---
  - name: install logstash
    apt:
      name: logstash

  - name: enable service
    service:
      name: logstash
      state: started
      enabled: true

  - name: configure logstash input
    template:
      src: input.conf.j2
      dest: /etc/logstash/conf.d/input.conf
    notify: restart logstash

  - name: configure logstash output
    template:
      src: output.conf.j2
      dest: /etc/logstash/conf.d/30-elasticsearch-output.conf
    notify: restart logstash
