---
  - name: Get nginx
    apt:
      name: nginx
      state: present
      

  - name: configure
    template:
      src: default.j2
      dest: /etc/nginx/sites-enabled/default
    notify: restart nginx
